[package]
name = "mi_motor"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
device_query = "0.2"
piston_window = "0.132.0"
rand = "0.8"
mlua = { version = "0.10.3", default-features = false, features = ["lua54"] }